### ISSUE TITLE
Cannot compile library from source

### ISSUE THREAD

**Issue by the-gremlin** [deltaphc/raylib-rs#132]
When compiling the library by cloning the repo and running `cargo build`, I get the following error, which is caused by PR #128. 
```
error[E0308]: mismatched types
  --> raylib/src/core/input.rs:59:35
   |
59 |             return char::from_u32(char_code as i32);
   |                                   ^^^^^^^^^^^^^^^^ expected `u32`, found `i32`
   |
help: you can convert an `i32` to a `u32` and panic if the converted value doesn't fit
   |
59 |             return char::from_u32((char_code as i32).try_into().unwrap());
   |                                   +                +++++++++++++++++++++
```

Note that `ffi::GetCharPressed()` returns an `i32` so the return statement should be 
```rs
return char::from_u32(char_code as u32);
```

**Comment by the-gremlin** [comment]
This issue will be resolved with the merging of PR #130.

**Comment by the-gremlin** [comment]
#130 was merged so im closing the issue
